version: '3.9'

services:
  tv_database:
    container_name:
      tv_database
    image:
      postgres:alpine3.18
    restart:
      always
    volumes:
      - ./scripts/db:/opt/db/
    env_file:
      - ./dotenv_files/.env.docker
    ports:
      - "5432:5432"

  tv_backend:
    container_name:
      tv_backend
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.backend
    env_file:
      - ./dotenv_files/.env.dev
    depends_on:
      - tv_database
    links:
      - tv_database:tv_database
    ports:
      - "8000:8000"
    tty: true
